version: '3.3'

volumes:
  pg_data-mishgan325:
  static-mishgan325:
  media-mishgan325:

services:
  db-mishgan325:
    image: postgres:13
    volumes:
      - pg_data-mishgan325:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  backend-mishgan325:
    image: mishgan325/foodgram_final-backend
    build: ../backend/
    env_file: .env
    volumes:
      - static-mishgan325:/app/collected_static/
      - media-mishgan325:/app/media/
    depends_on:
      - db-mishgan325
    entrypoint: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py load_ingredients ingredients.json &&
        echo \"from django.contrib.auth import get_user_model; User = get_user_model(); \
      if not User.objects.filter(email='admin@admin.admin').exists(): User.objects.create_superuser('admin', 'admin@admin.admin', 'admin123', first_name='admin', last_name='admin')\" | python manage.py shell &&
        gunicorn foodgram_backend.wsgi:application --bind 0.0.0.0:8000
      "

  frontend-mishgan325:
    image: mishgan325/foodgram_final-frontend
    container_name: foodgram-front-mishgan325
    build: ../frontend
    volumes:
      - ../frontend/build:/app/result_build/

  nginx-mishgan325:
    container_name: foodgram-proxy-mishgan325
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static-mishgan325:/static/
      - media-mishgan325:/media/